# import = [
# "~/.config/alacritty/catppuccin-mocha.toml"
# ]

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
dynamic_padding = true
opacity = 0.85

[colors.primary]
# background = "#000000"


